{
    'name': 'Helpdesk Community',
    'version': '19.0.1.0.3',
    'category': 'Services/Helpdesk',
    'summary': 'Helpdesk / Support Ticket Management - Community Edition',
    'description': 'Full-featured helpdesk and support ticket management. Free, open-source, and production-ready.',
    'author': 'FoxPink',
    'website': 'https://github.com/FoxPinkHQ/helpdesk-community',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'portal', 'web'],
    'data': [
        'security/helpdesk_groups.xml',
        'security/helpdesk_security.xml',
        'security/ir.model.access.csv',
        'data/helpdesk_sequence.xml',
        'data/helpdesk_data.xml',
        'data/mail_templates.xml',
        'views/helpdesk_ticket_views.xml',
        'views/helpdesk_ticket_kanban.xml',
        'views/helpdesk_stage_views.xml',
        'views/helpdesk_team_views.xml',
        'views/helpdesk_category_views.xml',
        'views/portal_tickets.xml',
        'views/helpdesk_menu.xml',
    ],
    'demo': [
        'demo/helpdesk_demo.xml',
    ],
    'images': ['static/description/banner.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
